# -*- coding: utf-8 -*-


from scrapy.item import Item,Field


class HuxiuItem(Item):

    huxiuNo = Field()
    Name = Field()
    Website = Field()
    CompanyName = Field()
    FoundDate = Field()
    District = Field()
    CompanyScale = Field()
    FinancingStage = Field()
    Tag = Field()
    Intro = Field()
    BreifIntro = Field()

    FinancingStage1 = Field()
    FinancingDate1 = Field()
    FinancingVC1 = Field()
    FinancingAmount1 = Field()
    FinancingUnit1 = Field()
    FinancingStage2 = Field()
    FinancingDate2 = Field()
    FinancingVC2 = Field()
    FinancingAmount2 = Field()
    FinancingUnit2 = Field()
    FinancingStage3 = Field()
    FinancingDate3 = Field()
    FinancingVC3 = Field()
    FinancingAmount3 = Field()
    FinancingUnit3 = Field()
    FinancingStage4 = Field()
    FinancingDate4 = Field()
    FinancingVC4 = Field()
    FinancingAmount4 = Field()
    FinancingUnit4 = Field()
    FinancingStage5 = Field()
    FinancingDate5 = Field()
    FinancingVC5 = Field()
    FinancingAmount5 = Field()
    FinancingUnit5 = Field()

    Founders1 = Field()
    Position1 = Field()
    FounderIntro1 = Field()
    Founders2 = Field()
    Position2 = Field()
    FounderIntro2 = Field()
    Founders3 = Field()
    Position3 = Field()
    FounderIntro3 = Field()
    Founders4 = Field()
    Position4 = Field()
    FounderIntro4 = Field()
    Founders5 = Field()
    Position5 = Field()
    FounderIntro5 = Field()
